-- Create questions table
CREATE TABLE IF NOT EXISTS public.questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_text TEXT NOT NULL,
    options JSONB NOT NULL, -- Array of strings
    correct_answer INTEGER NOT NULL, -- Index 0-3
    topic TEXT NOT NULL,
    elo_rating INTEGER DEFAULT 1200,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;

-- Allow read access to everyone
CREATE POLICY "Allow public read access" ON public.questions FOR SELECT USING (true);

-- Add questions column to rooms table if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'rooms' AND column_name = 'questions') THEN
        ALTER TABLE public.rooms ADD COLUMN questions JSONB;
    END IF;
END $$;

-- Create RPC function to get questions by ELO
CREATE OR REPLACE FUNCTION get_questions_by_elo(user_elo INT, limit_count INT DEFAULT 5)
RETURNS SETOF public.questions
LANGUAGE sql
AS $$
  SELECT *
  FROM public.questions
  ORDER BY ABS(elo_rating - user_elo) ASC
  LIMIT limit_count;
$$;

-- Create user_topic_stats table
CREATE TABLE IF NOT EXISTS public.user_topic_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL, -- Assuming auth.users or public.users
    topic TEXT NOT NULL,
    total_answered INTEGER DEFAULT 0,
    total_correct INTEGER DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, topic)
);

-- Enable RLS for stats
ALTER TABLE public.user_topic_stats ENABLE ROW LEVEL SECURITY;

-- Policies for stats
CREATE POLICY "Users can view their own stats" ON public.user_topic_stats FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can update their own stats" ON public.user_topic_stats FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own stats" ON public.user_topic_stats FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Seed data (Clear existing first to avoid duplicates if re-running)
TRUNCATE public.questions RESTART IDENTITY CASCADE;

INSERT INTO public.questions (question_text, options, correct_answer, topic, elo_rating) VALUES
-- ==================== ARITMATIKA (13 soal) ====================
-- ELO 400-800 (SD Kelas 1-3)
('Berapa hasil dari 5 + 8?', '["11", "12", "13", "14"]', 2, 'Aritmatika', 450),
('Berapa hasil dari 15 - 7?', '["6", "7", "8", "9"]', 2, 'Aritmatika', 500),
('Berapa hasil dari 6 × 4?', '["20", "22", "24", "26"]', 2, 'Aritmatika', 550),
('Berapa hasil dari 20 ÷ 5?', '["3", "4", "5", "6"]', 1, 'Aritmatika', 600),
('Berapa hasil dari 12 + 15 - 9?', '["16", "17", "18", "19"]', 2, 'Aritmatika', 750),

-- ELO 800-1000 (SD Kelas 4-6)
('Berapa hasil dari 15 × 8?', '["110", "120", "125", "130"]', 1, 'Aritmatika', 850),
('Hasil dari 144 ÷ 12 adalah?', '["10", "11", "12", "13"]', 2, 'Aritmatika', 900),
('Berapa 10% dari 500?', '["10", "50", "100", "5"]', 1, 'Aritmatika', 950),
('Berapa 1/4 dari 80?', '["15", "20", "25", "30"]', 1, 'Aritmatika', 900),
('Berapa hasil dari 25 × 16?', '["350", "400", "450", "500"]', 1, 'Aritmatika', 950),

-- ELO 1000-1200 (SMP Kelas 7-8)
('Berapa hasil dari (-5) + 12?', '["5", "6", "7", "17"]', 2, 'Aritmatika', 1050),
('Berapa hasil dari 2³ + 3²?', '["13", "15", "17", "19"]', 2, 'Aritmatika', 1100),
('Jika 3/5 dari suatu bilangan adalah 60, berapa bilangan tersebut?', '["90", "100", "110", "120"]', 1, 'Aritmatika', 1150),

-- ==================== ALJABAR (13 soal) ====================
-- ELO 600-800 (SD Kelas 2-3, pola sederhana)
('Lengkapi pola: 2, 4, 6, 8, ...', '["9", "10", "11", "12"]', 1, 'Aljabar', 650),
('Lengkapi pola: 5, 10, 15, 20, ...', '["22", "24", "25", "30"]', 3, 'Aljabar', 700),
('Lengkapi pola: 1, 3, 5, 7, ...', '["8", "9", "10", "11"]', 1, 'Aljabar', 750),

-- ELO 800-1000 (SD Kelas 4-6)
('Jika 5 + x = 12, berapa nilai x?', '["5", "6", "7", "8"]', 2, 'Aljabar', 850),
('Jika x - 8 = 15, berapa nilai x?', '["20", "21", "23", "25"]', 2, 'Aljabar', 900),
('Lengkapi pola: 2, 4, 8, 16, ...', '["20", "24", "28", "32"]', 3, 'Aljabar', 950),
('Jika 3 × x = 24, berapa nilai x?', '["6", "7", "8", "9"]', 2, 'Aljabar', 900),

-- ELO 1000-1200 (SMP Kelas 7-8)
('Jika x + 12 = 27, berapa nilai x?', '["12", "15", "18", "21"]', 1, 'Aljabar', 1050),
('Jika 3x = 21, maka x = ?', '["5", "6", "7", "8"]', 2, 'Aljabar', 1050),
('Jika 2x + 5 = 17, berapa nilai x?', '["4", "5", "6", "7"]', 2, 'Aljabar', 1100),
('Berapa nilai x jika 4x - 8 = 20?', '["5", "6", "7", "8"]', 2, 'Aljabar', 1150),
('Jika x² = 64, berapa nilai x yang positif?', '["6", "7", "8", "9"]', 2, 'Aljabar', 1150),
('Berapa akar pangkat dua dari 144?', '["10", "11", "12", "14"]', 2, 'Aljabar', 1100),

-- ==================== GEOMETRI (12 soal) ====================
-- ELO 500-800 (SD Kelas 1-3)
('Berapa sisi pada segitiga?', '["2", "3", "4", "5"]', 1, 'Geometri', 550),
('Berapa sisi pada persegi?', '["2", "3", "4", "5"]', 2, 'Geometri', 600),
('Sudut siku-siku besarnya berapa derajat?', '["45°", "90°", "180°", "360°"]', 1, 'Geometri', 750),

-- ELO 800-1000 (SD Kelas 4-6)
('Berapa keliling persegi dengan sisi 7 cm?', '["21 cm", "24 cm", "28 cm", "35 cm"]', 2, 'Geometri', 850),
('Berapa luas persegi dengan sisi 9 cm?', '["72 cm²", "81 cm²", "90 cm²", "99 cm²"]', 1, 'Geometri', 900),
('Berapa luas persegi panjang dengan panjang 8 cm dan lebar 5 cm?', '["30 cm²", "35 cm²", "40 cm²", "45 cm²"]', 2, 'Geometri', 900),
('Berapa keliling persegi panjang dengan panjang 10 cm dan lebar 6 cm?', '["26 cm", "28 cm", "30 cm", "32 cm"]', 3, 'Geometri', 950),
('Berapa luas segitiga dengan alas 10 cm dan tinggi 6 cm?', '["25 cm²", "30 cm²", "35 cm²", "60 cm²"]', 1, 'Geometri', 1000),

-- ELO 1000-1200 (SMP Kelas 7-8)
('Berapa volume kubus dengan sisi 4 cm?', '["48 cm³", "56 cm³", "64 cm³", "72 cm³"]', 2, 'Geometri', 1050),
('Volume kubus dengan sisi 5 cm adalah?', '["100 cm³", "125 cm³", "150 cm³", "25 cm³"]', 1, 'Geometri', 1100),
('Berapa luas lingkaran dengan jari-jari 7 cm? (π = 22/7)', '["144 cm²", "154 cm²", "164 cm²", "174 cm²"]', 1, 'Geometri', 1150),
('Berapa volume balok dengan panjang 6 cm, lebar 4 cm, dan tinggi 5 cm?', '["100 cm³", "110 cm³", "120 cm³", "130 cm³"]', 2, 'Geometri', 1150),

-- ==================== STATISTIKA (12 soal) ====================
-- ELO 900-1000 (SD Kelas 6) - fokus mean, median, modus
('Rata-rata dari 5, 8, 10, 12 adalah?', '["8", "8.5", "8.75", "9"]', 2, 'Statistika', 900),
('Rata-rata dari 6, 7, 8, 9, 10 adalah?', '["7", "8", "9", "10"]', 1, 'Statistika', 900),
('Median dari data 3, 5, 7, 9, 11 adalah?', '["5", "6", "7", "8"]', 2, 'Statistika', 920),
('Median dari data 4, 6, 8, 10 adalah?', '["6", "7", "8", "9"]', 1, 'Statistika', 920),
('Modus dari data 2, 3, 3, 4, 5, 5, 5, 6 adalah?', '["3", "4", "5", "6"]', 2, 'Statistika', 950),
('Modus dari data 7, 8, 8, 9, 9, 9, 10 adalah?', '["7", "8", "9", "10"]', 2, 'Statistika', 950),
('Rata-rata dari 10, 15, 20, 25, 30 adalah?', '["18", "20", "22", "25"]', 1, 'Statistika', 970),
('Median dari data 12, 15, 18, 21, 24 adalah?', '["15", "16", "18", "21"]', 2, 'Statistika', 970),
('Jika ada data: 5, 6, 7, 8, 9. Berapa rata-ratanya?', '["6", "6.5", "7", "7.5"]', 2, 'Statistika', 980),
('Data: 2, 4, 6, 8. Berapa mediannya?', '["4", "5", "6", "7"]', 1, 'Statistika', 980),
('Modus dari 10, 12, 12, 14, 16, 16, 16, 18 adalah?', '["12", "14", "16", "18"]', 2, 'Statistika', 1000),
('Rata-rata dari 20, 25, 30, 35, 40 adalah?', '["25", "28", "30", "32"]', 2, 'Statistika', 1000)
ON CONFLICT DO NOTHING;
